/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package juego;

/**
 *
 * @author Estudiantes
 */
public class Grafica extends javax.swing.JPanel {

    //En turno vamos a definir si es una X o una Y
    //0 es X
    //1 es Y
    int turno=0;
    
    /**
     * Creates new form Tablero
     */
    public Grafica() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Ficha01 = new javax.swing.JButton();
        Ficha02 = new javax.swing.JButton();
        Ficha21 = new javax.swing.JButton();
        Ficha11 = new javax.swing.JButton();
        Ficha12 = new javax.swing.JButton();
        Ficha20 = new javax.swing.JButton();
        Ficha00 = new javax.swing.JButton();
        Ficha10 = new javax.swing.JButton();
        Ficha22 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Castellar", 3, 36)); // NOI18N
        jLabel1.setText("TRIQUI");

        Ficha01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Ficha01MouseClicked(evt);
            }
        });
        Ficha01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ficha01ActionPerformed(evt);
            }
        });

        Ficha21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ficha21ActionPerformed(evt);
            }
        });

        Ficha11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ficha11ActionPerformed(evt);
            }
        });

        Ficha12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ficha12ActionPerformed(evt);
            }
        });

        Ficha00.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Ficha00MouseClicked(evt);
            }
        });
        Ficha00.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ficha00ActionPerformed(evt);
            }
        });

        Ficha10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ficha10ActionPerformed(evt);
            }
        });

        Ficha22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ficha22ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(Ficha00, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Ficha01, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Ficha02, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 18, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(94, 94, 94))
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Ficha20, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Ficha21, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Ficha22, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Ficha10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Ficha11, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(Ficha12, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Ficha01, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ficha00, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ficha02, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Ficha11, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ficha10, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ficha12, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Ficha21, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ficha20, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ficha22, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(72, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Ficha00ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ficha00ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ficha00ActionPerformed

    private void Ficha00MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Ficha00MouseClicked

        if(turno==0){
            this.Ficha01.setText("X");
            turno=1;
        }else{
            this.Ficha01.setText("Y");
            turno=0;
        }


        // TODO add your handling code here:
    }//GEN-LAST:event_Ficha00MouseClicked

    private void Ficha01MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Ficha01MouseClicked

        if(turno==0){
            this.Ficha01.setText("X");
            turno=1;
        }else{
            this.Ficha01.setText("Y");
            turno=0;
        }



    }//GEN-LAST:event_Ficha01MouseClicked

    private void Ficha22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ficha22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ficha22ActionPerformed

    private void Ficha01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ficha01ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ficha01ActionPerformed

    private void Ficha21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ficha21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ficha21ActionPerformed

    private void Ficha10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ficha10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ficha10ActionPerformed

    private void Ficha11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ficha11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ficha11ActionPerformed

    private void Ficha12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ficha12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ficha12ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Ficha00;
    private javax.swing.JButton Ficha01;
    private javax.swing.JButton Ficha02;
    private javax.swing.JButton Ficha10;
    private javax.swing.JButton Ficha11;
    private javax.swing.JButton Ficha12;
    private javax.swing.JButton Ficha20;
    private javax.swing.JButton Ficha21;
    private javax.swing.JButton Ficha22;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
